### ISSUE TITLE
Can't select local storage in open dialog

### ISSUE THREAD

**Issue by TizianoNoto** [maxistar/TextPad#15]
Hi Maxim

My smartphone just updated the app to version 1.12.0

Now, after tapping "Open", I don't have an option to browse files in local storage (internal and SD card), as you can see in the following screenshot:
![Screenshot_2021-02-07-18-07-19](https://user-images.githubusercontent.com/42154401/107153815-c6a63600-696f-11eb-9a07-30795f6e0891.png)

Is this the expected behavior or am I doing something wrong?

Android version is 4.4.2

**Comment by maxistar** [comment]
Hi @TizianoNoto , you should activate the local storage in the context menu of the file selector dialog. There should e something like "show local files" or something.

**Comment by TizianoNoto** [comment]
You're right, I didn't realize there was a context menu. The menu icon is hidden because I have a physical button... thank you Samsung.
I checked "Show advanced device options" (or whatever is in english) and it worked!
Thank you
