### ISSUE TITLE
Italian translation to be fixed

### ISSUE THREAD

**Issue by TizianoNoto** [maxistar/TextPad#16]
Hi again

The italian localisation needs some fixes, as I noticed a typo and other minor mistakes.

I can do it if you want, of course it will be based on the english version as I only know three russian words (guess which ones). Do I just need to update _app/src/main/res/values-it/strings.xml_ and make a pull request?

Best regards

**Comment by maxistar** [comment]
Hi @TizianoNoto ! Yes please, I would really appreciate your pull request!

**Comment by maxistar** [comment]
also if you would tell me how I can fix Italian strings I can do it by myself. Il mio italiano non è così buono.

**Comment by TizianoNoto** [comment]
Hi @maxistar I'm sorry but I had to deal with other things and I've forgotten to push my edits

I'll be able to open a pull request this evening

**Comment by TizianoNoto** [comment]
> Il mio italiano non è così buono.
No problem, I can help mantain the translation if you wish
