### ISSUE TITLE
improvement of Spanish translation (es_ES)

### ISSUE THREAD

**Issue by alimoche** [maxistar/TextPad#17]
the attached patch is an improvement of Spanish translation (es_ES), I used the English file instead of the current translation to have a hint of the translations. The improvement would make the translation more consistent with other applications, please consider the patch and/or amend it if any error, thank you

[es_ES.patch.zip](https://github.com/maxistar/TextPad/files/6061142/es_ES.patch.zip)

**Comment by maxistar** [comment]
Thank you! Added in the application!

**Comment by alimoche** [comment]
good job with this application! I tested the new version and it works very well thank you,  however, I saw when I was testing the editor that I overlooked one translation that was better in previous version and I have fixed it in a new patch  (also included a small change in 3 others but not important) sorry for the mistake.

[es_ES-2.patch.zip](https://github.com/maxistar/TextPad/files/6067814/es_ES-2.patch.zip)

**Comment by maxistar** [comment]
Thanks! Added new translation into the new release.
