### ISSUE TITLE
Undo Editing Feature?

### ISSUE THREAD

**Issue by cusco-travel-services** [maxistar/TextPad#18]
Hi Maxim,

Finally, an app that has a proper interface for accessing the Files. Well done!

Does the latest version have an Undo feature?

If so, do you know when it will be available on F-Droid?

If you need any help with Spanish, let me know.

Thanks!

**Comment by maxistar** [comment]
the undo and redo added the latest version it will be available on 10% percent of devices for the beginning and then increased to all others if there will be no problems.
I have created merge request for f-droid as soon it will be approved this version will also released.
