### ISSUE TITLE
Licensing data

### ISSUE THREAD

**Issue by siso-anu** [maxistar/TextPad#34]
Hi,
Could you update the licensing details.

Specifically wanted to know whether i can take the code and use it freely(i.e., Apache/MIT license)

Regards
Anu

**Comment by maxistar** [comment]
Hi @siso-anu thanks for the request, I think MIT License would be the good option. If there are no better suggestions I will add it to source code.

**Comment by siso-anu** [comment]
Hi,
Thanks for the prompt response.
We discovered in one of the readme files a link to textpad on F-Droid (
https://f-droid.org/packages/com.maxistar.textpad/)
Here it is mentioned as GNU GPL License.
Regards
