### ISSUE TITLE
Unable to save files on sdcard 

### ISSUE THREAD

**Issue by Agarwal-Nikhil** [maxistar/TextPad#53]
I was able to open a txt file on my sdcard but I am unable to save the existing file after editing. Error: cannot write file.

**Comment by herrdeh** [comment]
This may be related:
I can only save a file to the SD card's root directory. Whenever I "save to" any place, the file goes there and needs to be copied.

The "save" feature does not work as well, I get a "file could not be written" message. "save as" works, but only to SD card's root dir.

This happens at a Pixel 3a with LineageOS19; but similar problems occurred on a Galaxy 5s and a LG 3G, both with LineageOS.
