### ISSUE TITLE
handle Android 10 Light/Dark themes

### ISSUE THREAD

**Issue by StevanWhite** [maxistar/TextPad#91]
For Android 10 and higher, it is good to handle the system's Light and Dark themes.
If you do that, you can probably also drop the settings for color, when running on modern systems.

https://developer.android.com/develop/ui/views/theming/darktheme

**Comment by LinuxOnTheDesktop** [comment]
I would indeed be good to handle light and dark themes. The app does allow one to set foreground and background colours manually - so all would be well enough, except that the colour picker is the worst that I have experience. The picker does not allow manual entry of colour codes and I found selecting a dark colour to be very hard and selecting a white colour to be impossible.

**Comment by StevanWhite** [comment]
I don't understand your remark.

The system light/dark should be automatic, and the default behavior, requiring no user intervention.

As developer, you would specify colors for the system light and dark via resource files.
It's really pretty easy.

**Comment by LinuxOnTheDesktop** [comment]
@StevanWhite: like you, I think that the app ought to - but currently does not - switch theme automatically. My point about the colour picker was twofold, I suppose. To wit: (1) a good colour picker would be work-around for the lack of the aforementioned theme-switching; (2) at present the app's colour picker is not good.

**Comment by maxistar** [comment]
feature added in v1.26.0 the legacy color picker still here, some people like it.
